language: python

python:
  - '2.7'
  - '3.5'

install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip list
  - pip show osmnet

script:
  - pycodestyle osmnet
  - py.test --cov osmnet --cov-report term-missing

after_success:
  - coveralls
  - bin/build_docs.sh
