language: python

python:
  - '3.8'
  - '3.9'
  - '3.10'

install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip list
  - pip show osmnet

script:
  - pycodestyle --max-line-length=100 osmnet
  - py.test --cov osmnet --cov-report term-missing

after_success:
  - coveralls
