language: python

python:
  - '3.5'
  - '3.6'
#  - '3.7' # drop tests in 3.7 for now due to Travis build error
  - '3.8'

install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip list
  - pip show osmnet

script:
  - pycodestyle --max-line-length=100 osmnet
  - py.test --cov osmnet --cov-report term-missing

after_success:
  - coveralls
