language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'

matrix:
  include:
    - python: "3.7"  # temp solution to test in python 3.7
      dist: xenial
      sudo: true

install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip list
  - pip show osmnet

script:
  - pycodestyle osmnet
  - py.test --cov osmnet --cov-report term-missing

after_success:
  - coveralls
  - bin/build_docs.sh
