build: false

environment:
  matrix:
    - PYTHON: 3.8

init:
  - "ECHO %PYTHON%"

# The goal here is to make sure updates to OSMnet don't introduce any Windows-specific
# runtime errors; the Travis tests running in Linux are more comprehensive. Dependencies
# are installed manually here because the shapely/geopandas stack doesn't install well
# via Pip on Windows. Only using one Python version because AppVeyor builds don't run in
# parallel and can be slow.

install:
  - "set PATH=C:\\Miniconda3;C:\\Miniconda3\\Scripts;%PATH%"
  - "conda create --name test-env python=%PYTHON% pip --yes --quiet"
  - activate test-env
  - conda install geopandas numpy pandas pytest requests shapely --channel conda-forge
  - pip install .
  - conda list

test_script:
  - py.test
